apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: recebe-video-hpa
  namespace: hackathon-fiap
  labels:
    app.kubernetes.io/name: recebe-video-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: recebe-video-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 65