apiVersion: v1
kind: Service
metadata:
  name: recebe-video-svc
  namespace: hackathon-fiap
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: recebe-video-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30082